### ISSUE TITLE
Fraud alert / liability disclaimer

### ISSUE THREAD

**Issue by ann-kilzer** [ourjapanlife/findadoc-frontend#159]
- [x] update the fraud alert to use i18n
- [x] add Japanese translation to fraud alert
- 🏉  Add further liability disclaimer to the About page PUNT to #163 
- [x] translate to Japanese

**Comment by renderf0x** [comment]
Generating key and JA translation now.

**Comment by renderf0x** [comment]
https://github.com/ourjapanlife/findadoc-localization/pull/61

**Comment by renderf0x** [comment]
A couple of resources to add here for reference:

1. A template for a medical disclaimer (UK):
https://seqlegal.com/free-legal-documents/medical-disclaimer

2. A doctor finding site's liability page (Japanese):
https://www.10man-doc.co.jp/warning/

I think both are useful references. In our case we'll want to have info from both sides, but lean heavily on the JP side since we are in JP. 

I'd suggest we create a separate disclaimers page like they have on the latter, and link to it from the about page.
