### ISSUE TITLE
Add resiliency to testimonial component

### ISSUE THREAD

**Issue by ann-kilzer** [ourjapanlife/findadoc-frontend#193]
The testimonial component might show up empty if the tweet has been deleted. See here: https://github.com/ourjapanlife/findadoc-frontend/pull/192

It would be great if we could detect this and be more robust.

**Comment by renderf0x** [comment]
I wish they'd merge this CR, as this could be easily used for this:
https://github.com/tonickkozlov/vue-tweet-embed/pull/58

**Comment by renderf0x** [comment]
Blocked on the design from @thehamspecial for the testimonials area / page, as that will define what the component should do (render a random different tweet? not render?) based on how many are in the layout, etc.

I think this will need to be a fresh component for Tweets instead of the lib we're using, but that should be easy enough given that Twitter's embed lib looks pretty straightforward.

**Comment by renderf0x** [comment]
Working off of @thehamspecial 's current mock of the page to add the new styling to this component too:
https://www.figma.com/proto/kdgcV9gd3cOeiSgoXY6VLM/Find-a-Doc?node-id=4%3A16&scaling=fit-width&page-id=0%3A1&hotspot-hints=0&hide-ui=1

@thehamspecial - do you have a mock for what you'd want this Twitter component to look like on a small screen size?

**Comment by thehamspecial** [comment]
@renderf0x Yup, [here's](https://www.figma.com/proto/kdgcV9gd3cOeiSgoXY6VLM/Find-a-Doc?node-id=45%3A1373&scaling=min-zoom&page-id=0%3A1&hotspot-hints=0&hide-ui=1) the layout on small screens.

[Here's](https://www.figma.com/proto/kdgcV9gd3cOeiSgoXY6VLM/Find-a-Doc?node-id=42%3A826&scaling=min-zoom&page-id=0%3A1&hotspot-hints=0&hide-ui=1) the desktop view. Let me know if you have feedback!

**Comment by renderf0x** [comment]
Looks great @thehamspecial - will work on getting the Twitter portion up and running.
