### ISSUE TITLE
Admin Dashboard Logger

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-frontend#202]
Implement a logger for the admin dashboard to keep track of which moderator performed which actions.

**Comment by ann-kilzer** [comment]
Ahh like an audit log, great call

**Comment by ermish** [comment]
We have a ticket open for us to choose a production client side logger which should work for this! 
I think we can simply use the regular 'logger' here and log the details of transaction. 

Firebase might actually have some backend logging we can utilize as well

**Comment by renderf0x** [comment]
So, I actually think that we should not use a logger for this, but rather create an audit table with a specific event format.

Here's my reasoning - in the future, we'll want to track updates on specific clinic entries, and potentially even be able to see this from the admin page for a clinic. Also rather than deleting items from the DB, we should instead just mark them as inactive/deleted as a field. In this world, we could restore these entries, as well as understand who deleted them and why.

Introspecting and using these logs as an admin will be much easier if it's available on page as opposed to needing to go log-spelunking.

Unless of course, as you say, Firebase has a built in transaction logger. That would be an ok stopgap for now.

**Comment by ermish** [comment]
I should have clarified. I think we can use a front-end logger for having SOMETHING stood up and it will be good to have for our logging. However, this isn't a reliable long-term solution since it's not trustworthy. 

We will need something on the backend to log....
I've looked and firebase does not provide ANY logs we can use for firestore db :(

However, we can write a function that's triggered on any db change and it writes to a log. This seems to be the standard practice. Since we don't have a backend/API for now, this seems to be the best option, but would be open to others!

Also, +1 for soft deletes @renderf0x! It might complicate queries and make a small hit to perf, but I think it's the simplest option. (event systems are hard)
