### ISSUE TITLE
figure out how to use i18n in <script>

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-frontend#31]
In general, we can use `this.$t("whatever")` in the script.

But in the validations, this wasn't working. 

We found a similar issue on Stack Overflow: https://stackoverflow.com/questions/57568660/using-i18n-in-nuxt-plugin

We also have been asking in Discord: 

Update: Discord member tells us "You have scope problem with your syntax" https://discord.com/channels/473401852243869706/484007829498232832/857161596546580500

**Comment by Al-un** [comment]
Some attempt done in #179 but not fully confident if that's the proper way. PR is still draft at the moment.

**Comment by Al-un** [comment]
Some cross-over with #20

**Comment by asile12** [comment]
Hi I was trying stuff out and the translations seem to be working fine for me? Maybe I didn't understand what the problem is...
This is the only code diff and the result ↓
![Screenshot from 2021-07-03 23-42-11](https://user-images.githubusercontent.com/50538104/124375724-9eccbb80-dcde-11eb-93c4-9b782ef3c615.png)
![Screenshot from 2021-07-03 23-40-33](https://user-images.githubusercontent.com/50538104/124375722-9d9b8e80-dcde-11eb-956e-9baa80aebc88.png)

**Comment by Al-un** [comment]
Hello @asile12 ,

I forgot to link back [a comment from my PR](https://github.com/ourjapanlife/findadoc-frontend/pull/179#issuecomment-871027742) here. I think when introducing Vuelidate, the i18n was also taken care so just asking for confirmation before closing this issue.

(_Note: associated PR is closed to avoid ambiguity_)
