### ISSUE TITLE
Inject build variables via netlify

### ISSUE THREAD

**Issue by ann-kilzer** [ourjapanlife/findadoc-frontend#68]
Should we inject configuration variables such as API keys into the build via Netlify?

It could be a good security and modularity practice. This page has info:

https://docs.netlify.com/configure-builds/environment-variables/

**Comment by ann-kilzer** [comment]
Should we set up a dev firebase account and distribute that API key? 🤔  Or overkill?

**Comment by renderf0x** [comment]
> Should we set up a dev firebase account and distribute that API key? 🤔 Or overkill?

As per #113 , it's either that (set up a general dev account) or provide instructions and an easy way to set up your own.
I think it depends on number of contributors - if we have alot, it'd be better IMO for them to have their own free-tier plans and use those, rather than us providing (which could potentially pop up the tier to a paid plan for dev too).
